version: '3.8'

services:
  simpradb:
    container_name: simpradb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - simpradb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Password12* 

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


