version: '3.8'

services:
  simpradb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  basketdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3.11.5-management

volumes:
  simpradb_volume:

